language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/main.cpp

install:
    - pip install -U platformio
    - platformio update
    # Libraries from PlatformIO Library Registry:
    # https://platformio.org/lib/show/5622/Bolder%20Flight%20Systems%20SBUS
    # https://platformio.org/lib/show/850/Plotter
    # https://platformio.org/lib/show/265/AccelStepper
    - platformio lib -g install 5622
    - platformio lib -g install 850
    - platformio lib -g install 265

script:
    - platformio ci --board=teensy36
